[package]
name = "mcglue"
version = "0.1.17"
edition = "2024"
license = "MPL-2.0"
homepage = "https://github.com/Vonr/mcglue"
repository = "https://github.com/Vonr/mcglue"

[dependencies]
async-signal = "0.2"
bstr = "1"
btoi = "0.5"
chumsky = "0.13"
color-eyre = "0.6"
dotenvy = "0.15"
eyre = "0.6"
flate2 = "1"
flume = "0.12"
jaq-core = "3"
jaq-std = "3"
menv = "0.2"
nbtq-core = { git = "https://github.com/Vonr/nbtq", version = "0.1.1" }
crab_nbt = { git = "https://github.com/Vonr/CrabNBT.git", branch = "nbtq", features = ["serde"] }
parking_lot = "0.12"
poise = "0.7"
reqwest = { version = "0.13", default-features = false, features = ["charset", "http2", "rustls", "system-proxy", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", default-features = false, features = ["macros", "parking_lot", "process", "rt-multi-thread", "signal"] }
tokio-util = { version = "0.7", default-features = false, features = [] }
uuid = { version = "1", features = ["v3", "v4"] }
walkdir = "2"
zip = { version = "9.0.0-pre3", default-features = false, features = ["zstd"] }
version-compare = "0.2"
iroh = { version = "1", default-features = false, features = ["tls-ring", "portmapper"], optional = true }
iroh-blobs = { version = "0.103", default-features = false, features = ["fs-store", "hide-proto-docs"], optional = true }
rand = "0.10"
tempfile = "3"
n0-future = { version = "0.3", optional = true }
humansize = { version = "2", features = ["no_alloc"] }
serenity = { version = "0.12.5", default-features = false, features = ["cache", "collector", "rustls_backend"] }
console-subscriber = { version = "0.5", optional = true }

[features]
default = ["iroh"]
full = ["default"]

iroh = ["dep:iroh", "dep:iroh-blobs", "dep:n0-future"]
tokio-console = ["dep:console-subscriber"]

[profile.release]
opt-level = 3
lto = "thin"
debug = 0
strip = true

[profile.release-with-debug]
inherits = "release"
debug = true
strip = false

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/{ version }/{ name }-{ version }-{ target }{ archive-suffix }"
bin-dir = "{ name }-{ version }-{ target }/{ bin }{ binary-ext }"
pkg-fmt = "tgz"
disabled-strategies = ["quick-install", "compile"]

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"

[package.metadata.binstall.overrides.x86_64-pc-windows-gnu]
pkg-fmt = "zip"

[package.metadata.docs.rs]
features = ["full"]
rustdoc-args = ["--cfg", "docsrs"]
